CREATE ROLE COLECCIONISTA;
GRANT SELECT,INSERT ON ALL TABLES IN SCHEMA public TO COLECCIONISTA;
CREATE USER coleccionista_user_1 WITH PASSWORD '123456';
GRANT COLECCIONISTA TO coleccionista_user_1;
CREATE ROLE IDENTIFICADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON kingdom TO IDENTIFICADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON phylum TO IDENTIFICADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON class TO IDENTIFICADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON "Order" TO IDENTIFICADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON family TO IDENTIFICADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Genus TO IDENTIFICADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON EpiteloEspecifico TO IDENTIFICADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Especimen TO IDENTIFICADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAXONOMIA TO IDENTIFICADOR;
GRANT SELECT, INSERT, UPDATE ON datosRecoleccion TO IDENTIFICADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON contribuidores TO IDENTIFICADOR;
GRANT SELECT ON Persona TO IDENTIFICADOR;
GRANT SELECT ON especies_pendientes TO IDENTIFICADOR;
GRANT EXECUTE ON FUNCTION Obtener_especimens(INT) TO IDENTIFICADOR;


GRANT SELECT, INSERT,UPDATE ON ALL TABLES IN SCHEMA public TO IDENTIFICADOR;
CREATE USER identificador_user WITH PASSWORD 'IdentifCE12';
GRANT IDENTIFICADOR TO identificador_user;

GRANT EXECUTE ON PROCEDURE identificar_especimen TO IDENTIFICADOR;
GRANT EXECUTE ON FUNCTION insertar_Epitelo(nameEpitelo TEXT) TO IDENTIFICADOR;
GRANT EXECUTE ON FUNCTION insertar_genus(nameGenus TEXT, idFamily INT) TO IDENTIFICADOR;
GRANT EXECUTE ON FUNCTION insertar_family(nameFamily TEXT, idOrder INT) TO IDENTIFICADOR;
GRANT EXECUTE ON FUNCTION insertar_order(nameOrder TEXT, idClass INT) TO IDENTIFICADOR;
GRANT EXECUTE ON FUNCTION insertar_class(nameClass TEXT, idPhylum INT) TO IDENTIFICADOR;
GRANT EXECUTE ON FUNCTION insertar_phylum(namePhylum TEXT, idKingdom INT) TO IDENTIFICADOR;
GRANT EXECUTE ON FUNCTION insertar_kingdom(nameKingdom TEXT) TO IDENTIFICADOR;
GRANT EXECUTE ON FUNCTION insertar_contribuidores(contribuidores TEXT,acciones TEXT,detalles TEXT,apellidos_paternos_contribuidores TEXT,apellidos_maternos_contribuidores TEXT,id_datos INT) TO IDENTIFICADOR;

CREATE ROLE PROFESOR;

ALTER ROLE PROFESOR WITH CREATEROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO PROFESOR;
GRANT USAGE ON SCHEMA public TO PROFESOR;

CREATE USER profesor_user_1 WITH PASSWORD '123456';
GRANT PROFESOR TO profesor_user_1;

-- USUARIO PARA EL LOGIN

CREATE ROLE USUARIOTEMP;
GRANT SELECT ON Persona TO USUARIOTEMP;
GRANT SELECT ON usuario TO USUARIOTEMP;
GRANT SELECT ON rol TO USUARIOTEMP;
GRANT SELECT ON trabajador TO USUARIOTEMP;

CREATE USER usuario_temporal WITH PASSWORD '123456';
GRANT USUARIOTEMP TO usuario_temporal;


CREATE ROLE PROFESOR;

ALTER ROLE PROFESOR WITH CREATEROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO PROFESOR;
GRANT USAGE ON SCHEMA public TO PROFESOR;

CREATE USER profesor_user_1 WITH PASSWORD '123456';
GRANT PROFESOR TO profesor_user_1;


