CREATE ROLE COLECCIONISTA;
GRANT SELECT,INSERT TO ALL TABLES IN SCHEMA public TO COLECCIONISTA;
CREATE USER coleccionista_user_1 WITH PASSWORD '123456';
GRANT COLECCIONISTA TO coleccionista_user_1;


CREATE ROLE IDENTIFICADOR;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO COLECCIONISTA;
CREATE USER identificador_user_1 WITH PASSWORD '123456';
GRANT IDENTIFICADOR TO identificador_user_1;


CREATE ROLE PROFESOR;

ALTER ROLE PROFESOR WITH CREATEROLE;
GRANT SELECT,INSERT,UPDATE,DELETE TO ALL TABLES IN SCHEMA public TO COLECCIONISTA;
GRANT USAGE ON SCHEMA public TO PROFESOR;

CREATE USER profesor_user_1 WITH PASSWORD '123456';
GRANT PROFESOR TO profesor_user_1;







