
-- Crear tablas
CREATE TABLE KINGDOM (
    ID_KINGDOM SERIAL PRIMARY KEY,
    NAME_KINGDOM TEXT NOT NULL
);

CREATE TABLE PHYLUM (
    ID_PHYLUM SERIAL PRIMARY KEY,
    NAME_PHYLUM TEXT NOT NULL,
    ID_REINO INT REFERENCES KINGDOM (ID_KINGDOM) ON DELETE CASCADE
);

CREATE TABLE CLASS (
    ID_CLASS SERIAL PRIMARY KEY,
    NAME_CLASS TEXT NOT NULL,
    ID_PHYLUM INT REFERENCES PHYLUM (ID_PHYLUM) ON DELETE CASCADE
);

CREATE TABLE TAXONOMIAORDER (
    ID_ORDER SERIAL PRIMARY KEY,
    NAME_ORDER TEXT NOT NULL,
    ID_CLASS INT REFERENCES CLASS (ID_CLASS) ON DELETE CASCADE
);

CREATE TABLE FAMILY (
    ID_FAMILY SERIAL PRIMARY KEY,
    NAME_FAMILY TEXT NOT NULL,
    ID_ORDER INT REFERENCES TAXONOMIAORDER (ID_ORDER) ON DELETE CASCADE
);

CREATE TABLE GENUS (
    ID_GENUS SERIAL PRIMARY KEY,
    GENUS TEXT NOT NULL,
    ID_FAMILY INT REFERENCES FAMILY(ID_FAMILY) ON DELETE CASCADE
);

CREATE TABLE EPITELOESPECIFICO (
    ID_SPECIFICEPITHET SERIAL PRIMARY KEY,
    EPITHET TEXT NOT NULL
);

CREATE TABLE ESPECIMEN (
    CATALOGNUMBER SERIAL PRIMARY KEY,
    SCIENTIFICNAME TEXT NOT NULL,
    LIFESTAGE TEXT,
    SEX TEXT,
    INDIVIDUALCOUNT INT
);

CREATE TABLE IMAGENES (
    ID_FOTO SERIAL PRIMARY KEY,
    URL TEXT NOT NULL
);

CREATE TABLE UBICACION (
    ID_UBICACION SERIAL PRIMARY KEY,
    LATITUD NUMERIC,
    LONGITUD NUMERIC,
    ALTITUD NUMERIC,
    LOCALITY TEXT,
    HABITAT TEXT,
    NOTAS TEXT
);

CREATE TABLE EVENTO_DE_COLECCION (
    ID_EVENTO_RECOLECCION SERIAL PRIMARY KEY,
    EVENT_DATE TIMESTAMP NOT NULL,
    ID_UBICACION INT REFERENCES UBICACION (ID_UBICACION) ON DELETE CASCADE
);

CREATE TABLE INFO_RECOLECCION (
    ID_RECOLECCION SERIAL PRIMARY KEY,
    EVENTO INT REFERENCES EVENTO_DE_COLECCION (ID_EVENTO_RECOLECCION) ON DELETE CASCADE
);

CREATE TABLE PERSONA (
    ID_PERSONA SERIAL PRIMARY KEY,
    NOMBRE TEXT NOT NULL,
    APELLIDO TEXT NOT NULL,
    EDAD INT CHECK (EDAD >= 0),
    TELEFONO TEXT,
    NACIONALIDAD TEXT
);

CREATE TABLE JERARQUIA (
    ID_JERARQUIA SERIAL PRIMARY KEY,
    NOMBRE TEXT NOT NULL
);

CREATE TABLE TRABAJADOR (
    ID_TRABAJADOR SERIAL PRIMARY KEY,
    TIPO_TRABAJADOR INT REFERENCES JERARQUIA (ID_JERARQUIA) ON DELETE SET NULL,
    ID_PERSONA INT REFERENCES PERSONA (ID_PERSONA) ON DELETE CASCADE
);

CREATE TABLE INSTITUTO (
    ID_INSTITUTO SERIAL PRIMARY KEY,
    NOMBRE TEXT NOT NULL,
    DIRECCION TEXT
);

CREATE TABLE TRABAJADOR_INSTITUCION (
    ID_TRABAJADOR INT REFERENCES TRABAJADOR (ID_TRABAJADOR),
    ID_INSTITUCION INT REFERENCES INSTITUTO (ID_INSTITUTO),
    PRIMARY KEY (ID_TRABAJADOR, ID_INSTITUCION)
);

CREATE TABLE INSTITUTO_COLECTAS (
    ID_INSTITUCION INT REFERENCES INSTITUTO (ID_INSTITUTO),
    ID_EVENTO_RECOLECCION INT REFERENCES EVENTO_DE_COLECCION (ID_EVENTO_RECOLECCION),
    PRIMARY KEY (ID_INSTITUCION, ID_EVENTO_RECOLECCION)
);

CREATE TABLE TAXON_COLECTA (
    ID_RECOLECCION INT REFERENCES INFO_RECOLECCION (ID_RECOLECCION),
    ESPECIMEN INT REFERENCES ESPECIMEN (CATALOGNUMBER),
    PRIMARY KEY (ID_RECOLECCION, ESPECIMEN)
);

CREATE TABLE PARTICIPACION_RECOLECCION (
    ID_RECOLECCION INT REFERENCES INFO_RECOLECCION (ID_RECOLECCION),
    ID_TRABAJADOR INT REFERENCES TRABAJADOR (ID_TRABAJADOR),
    PRIMARY KEY (ID_RECOLECCION, ID_TRABAJADOR)
);

CREATE TABLE ESPECIMEN_IMAGENES (
    ID_ESPECIMEN INT REFERENCES ESPECIMEN (CATALOGNUMBER),
    ID_FOTO INT REFERENCES IMAGENES (ID_FOTO),
    PRIMARY KEY (ID_ESPECIMEN, ID_FOTO)
);

CREATE TABLE TAXONOMIA (
    TAXONID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    ID_ESPECIMEN INT REFERENCES ESPECIMEN (CATALOGNUMBER),
    TIPO TEXT NOT NULL,
    SCIENTIFICNAME TEXT NOT NULL,
    KINGDOM INT REFERENCES KINGDOM (ID_KINGDOM) ON DELETE SET NULL,
    PHYLUM INT REFERENCES PHYLUM (ID_PHYLUM) ON DELETE SET NULL,
    CLASS INT REFERENCES CLASS (ID_CLASS) ON DELETE SET NULL,
    ORDER_TAXONOMIA INT REFERENCES TAXONOMIAORDER (ID_ORDER) ON DELETE SET NULL,
    FAMILY INT REFERENCES FAMILY(ID_FAMILY) ON DELETE SET NULL,
    GENUS INT REFERENCES GENUS (ID_GENUS) ON DELETE SET NULL,
    SPECIFICEPITHET INT REFERENCES EPITELOESPECIFICO (ID_SPECIFICEPITHET) ON DELETE SET NULL
);

-- Insertar reinos
INSERT INTO KINGDOM (NAME_KINGDOM) VALUES ('Animalia');

-- Insertar filos
INSERT INTO PHYLUM (NAME_PHYLUM, ID_REINO) VALUES ('Arthropoda', 1);

-- Insertar clases
INSERT INTO CLASS (NAME_CLASS, ID_PHYLUM) VALUES ('Insecta', 1);

-- Insertar órdenes
INSERT INTO TAXONOMIAORDER (NAME_ORDER, ID_CLASS) VALUES ('Coleoptera', 1);

-- Insertar familias
INSERT INTO FAMILY (NAME_FAMILY, ID_ORDER) VALUES ('Carabidae', 1);

-- Insertar géneros
INSERT INTO GENUS (GENUS, ID_FAMILY) VALUES ('Brachinus', 1);

-- Insertar epítetos específicos
INSERT INTO EPITELOESPECIFICO (EPITHET) VALUES ('crepitans');

-- Insertar ubicaciones
INSERT INTO UBICACION (LATITUD, LONGITUD, ALTITUD, LOCALITY, HABITAT, NOTAS) 
VALUES (19.4326, -99.1332, 2240, 'Ciudad de México', 'Bosque templado', 'Zona protegida con alta biodiversidad');

-- Insertar eventos de colección
INSERT INTO EVENTO_DE_COLECCION (EVENT_DATE, ID_UBICACION)
VALUES ('2024-01-15 10:00:00', 1);

-- Insertar información de recolección
INSERT INTO INFO_RECOLECCION (EVENTO) VALUES (1);

-- Insertar personas
INSERT INTO PERSONA (NOMBRE, APELLIDO, EDAD, TELEFONO, NACIONALIDAD)
VALUES ('Juan', 'Pérez', 35, '5551234567', 'Mexicana');

INSERT INTO PERSONA (NOMBRE, APELLIDO, EDAD, TELEFONO, NACIONALIDAD)
VALUES ('Ana', 'Gómez', 28, '5559876543', 'Mexicana');

-- Insertar jerarquías
INSERT INTO JERARQUIA (NOMBRE) VALUES ('Recolector');
INSERT INTO JERARQUIA (NOMBRE) VALUES ('Profesor');

-- Insertar trabajadores
INSERT INTO TRABAJADOR (TIPO_TRABAJADOR, ID_PERSONA) VALUES (1, 1);
INSERT INTO TRABAJADOR (TIPO_TRABAJADOR, ID_PERSONA) VALUES (2, 2);

-- Insertar institutos
INSERT INTO INSTITUTO (NOMBRE, DIRECCION) 
VALUES ('Instituto Nacional de Ecología', 'Av. Insurgentes Sur 123, Ciudad de México');

-- Relacionar trabajadores con institutos
INSERT INTO TRABAJADOR_INSTITUCION (ID_TRABAJADOR, ID_INSTITUCION) VALUES (1, 1);
INSERT INTO TRABAJADOR_INSTITUCION (ID_TRABAJADOR, ID_INSTITUCION) VALUES (2, 1);

-- Insertar especímenes
INSERT INTO ESPECIMEN (SCIENTIFICNAME, LIFESTAGE, SEX, INDIVIDUALCOUNT)
VALUES ('Brachinus crepitans', 'Adulto', 'Macho', 5);

-- Insertar imágenes
INSERT INTO IMAGENES (URL) VALUES ('https://example.com/brachinus1.jpg');

-- Relacionar especímenes con imágenes
INSERT INTO ESPECIMEN_IMAGENES (ID_ESPECIMEN, ID_FOTO) VALUES (1, 1);

-- Insertar taxonomía completa para el espécimen
INSERT INTO TAXONOMIA (ID_ESPECIMEN, TIPO, SCIENTIFICNAME, KINGDOM, PHYLUM, CLASS, ORDER_TAXONOMIA, FAMILY, GENUS, SPECIFICEPITHET)
VALUES (1, 'Insecto', 'Brachinus crepitans', 1, 1, 1, 1, 1, 1, 1);

-- Relacionar eventos de recolección con instituciones
INSERT INTO INSTITUTO_COLECTAS (ID_INSTITUCION, ID_EVENTO_RECOLECCION)
VALUES (1, 1);

-- Relacionar recolectores con eventos de recolección (participación)
INSERT INTO PARTICIPACION_RECOLECCION (ID_RECOLECCION, ID_TRABAJADOR)
VALUES (1, 1);

INSERT INTO PARTICIPACION_RECOLECCION (ID_RECOLECCION, ID_TRABAJADOR)
VALUES (1, 2);

-- Relacionar especímenes recolectados con información de recolección
INSERT INTO TAXON_COLECTA (ID_RECOLECCION, ESPECIMEN)
VALUES (1, 1);